### ISSUE TITLE
Models should be moved from nodes into BehaviorTree

### ISSUE THREAD

**Issue by RichardKelley** [RichardKelley/dendron#3]
Models are currently placed in Nodes (ex: `CausalLMAction`), but this means that if two nodes want to use the same model, extra work is required to prevent duplication and share the model.

Centralizing the models at the BehaviorTree level solves this.

Here are the TODOs to make this happen:

- [x] Model configs should be moved into their own files (#6).
- [x] Model config files should go into a `models` directory (#7).
- [x] `BehaviorTree` should be able to store configuration objects (#8).
- [x] `BehaviorTree` should maintain a mapping from model identifiers. This could just be the model name, but may need to include things like the quantization level (#9).
- [x] `BehaviorTree` interface should support operations to `add_model` and maybe `remove_model` given a config (or name, or object reference...) (#10).
- [x] Node interfaces should be updated to take a name or a config for a model, but should forward this to the `BehaviorTree` for model construction. Nodes should maintain read-only properties that point to their models in the enclosing `BehaviorTree` (#11).
- [x] Bump minor version (since we're changing the interface).

Each of these has or will have its own issue for detailed discussion.
