### ISSUE TITLE
Use HFLM for language models

### ISSUE THREAD

**Issue by RichardKelley** [RichardKelley/dendron#4]
Right now adding a node that uses any kind of LM requires custom code in the `tick` function. The [HFLM library](https://github.com/RichardKelley/hflm) handles loading models from the Hugging Face hub and presents a consistent interface for using different models. 

We should switch to using HFLM as much as possible. At present, this means everywhere except for VLMs, which aren't yet implemented.

Here are the TODOs for this switch:

- [x] Add `hflm` as a dependency for `dendron`. (#12)
- [x] Add new action node corresponding to HFLM's `loglikelihood` function. (#13)
- [x] Add new action node corresponding to HFLM's `loglikelihood_rolling` function. (#14)
- [x] Add new action node corresponding to HFLM's `generate_until` function. (#15)
- [x] Refactor `CompletionCondition` to split the probability calculation from the condition evaluation - use the new action node for `loglikelihood_rolling`. (#16)

**Comment by RichardKelley** [comment]
Closed by #20.
